--- 
android: 
  components: 
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17
language: android
script: 
  - "./gradlew check"
